### ISSUE TITLE
Design malaria upcoming services page

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#10]
The only service that would need to appear as upcoming would be the follow-up visit. 

However, the question becomes what would this look like for those with multiple services - ANC, PNC, child U5? @rowo Do you have any thoughts on this?

**Comment by rowo** [comment]
@msschroeder Is this taken care of via https://github.com/OpenSRP/opensrp-client-chw-malaria/issues/22 ?

**Comment by msschroeder** [comment]
@rowo I don't really think so: It is more like [this](https://github.com/OpenSRP/opensrp-client-chw-anc/issues/14). But, maybe I am not thinking about it the same way. Can you explain a little more about how #22 might achieve this?

**Comment by rowo** [comment]
@msschroeder My mistake, I may have been on the wrong issue at the time of my comment. 

For upcoming services if we're thinking the purpose of that page is to talk to a client on what's next up, I think it's okay to put them in chronological order. 

Since this is for an individual person, I don't think we'll run into the issue of someone being ANC and PNC and Child all at the same time — it would just be one of those and malaria. So I can see just slotting malaria in chronologically into that list in https://github.com/OpenSRP/opensrp-client-chw-anc/issues/14

**Comment by msschroeder** [comment]
Closing as I created #33
